/*FUNCION SUBE_ARCHIVO_REMATE*/
DROP FUNCTION	REMATE.SUBE_ARCHIVO_REMATE;

USE	REMATE;

DELIMITER $$
CREATE 	FUNCTION	REMATE.SUBE_ARCHIVO_REMATE
(
IN_ID_DETREMATE			INT,
IN_NOM_ARCHIVOREMATE	VARCHAR(100),
IN_DES_ARCHIVOREMATE	VARCHAR(200),
IN_URL_ARCHIVOREMATE	VARCHAR(200),
IN_TIP_ARCHIVOREMATE	VARCHAR(50),
IN_SIZ_ARCHIVOREMATE	INT(50)
)
RETURNS INT

DETERMINISTIC
BEGIN

INSERT	INTO	REMATE.REM_ARCHIVO_REMATE
(
ID_DETREMATE,
NOM_ARCHIVOREMATE,
DES_ARCHIVOREMATE,
URL_ARCHIVOREMATE,
TIP_ARCHIVOREMATE,
SIZ_ARCHIVOREMATE
)
VALUES
(
IN_ID_DETREMATE,		
IN_NOM_ARCHIVOREMATE,
IN_DES_ARCHIVOREMATE,
IN_URL_ARCHIVOREMATE,
IN_TIP_ARCHIVOREMATE,
IN_SIZ_ARCHIVOREMATE
);

RETURN 0;  
END$$
DELIMITER ;


    