/*FUNCION AGREGA_MAIL_REMATE*/
DROP FUNCTION	REMATE.AGREGA_MAIL_REMATE;

USE	REMATE;

DELIMITER $$
CREATE 	FUNCTION	REMATE.AGREGA_MAIL_REMATE
(
IN_NOM_MAILREMATE	VARCHAR(30),
IN_MSN_MAILREMATE	VARCHAR(50)
)
RETURNS INT

DETERMINISTIC
BEGIN

DECLARE	AUX_MAIL		INT;

SELECT	COUNT(*)
INTO	AUX_MAIL
FROM	REMATE.REM_MAIL_REMATE
WHERE	MSN_MAILREMATE	=	IN_MSN_MAILREMATE;

IF(AUX_MAIL>0) THEN
	RETURN 1;
ELSE

INSERT	INTO	REMATE.REM_MAIL_REMATE
(NOM_MAILREMATE,MSN_MAILREMATE)
VALUES
(IN_NOM_MAILREMATE,IN_MSN_MAILREMATE);

RETURN 0;  
END IF;
END$$
DELIMITER ;


    