/*FUNCION AGREGA_DET_REMATE*/
DROP FUNCTION	REMATE.AGREGA_DET_REMATE;

USE	E_VALE;

DELIMITER $$
CREATE 	FUNCTION	REMATE.AGREGA_DET_REMATE
(
IN_ID_DETREMATE		INT,
IN_GLS_DETREMATE	VARCHAR(30),
IN_DIR_DETREMATE	VARCHAR(50),
IN_FEC_DETREMATE	VARCHAR(20),
IN_DES_DETREMATE  	VARCHAR(8000)
)
RETURNS INT

DETERMINISTIC
BEGIN


UPDATE	REMATE.REM_DET_REMATE
SET 	GLS_DETREMATE 	=	IN_GLS_DETREMATE,
        DIR_DETREMATE 	=	IN_DIR_DETREMATE,
        FEC_DETREMATE 	=	IN_FEC_DETREMATE,
        DES_DETREMATE	=	IN_DES_DETREMATE
WHERE	ID_DETREMATE	=   IN_ID_DETREMATE;

RETURN 0;  

END$$
DELIMITER ;


    