/*FUNCION BORRA_DET_REMATE*/
DROP FUNCTION	REMATE.BORRA_DET_REMATE;

USE	REMATE;

DELIMITER $$
CREATE 	FUNCTION	REMATE.BORRA_DET_REMATE
(
IN_ID_DETREMATE		INT
)
RETURNS INT

DETERMINISTIC
BEGIN

DELETE	
FROM	REMATE.REM_ARCHIVO_REMATE
WHERE	ID_DETREMATE	=	IN_ID_DETREMATE;


UPDATE	REMATE.REM_DET_REMATE
SET 	GLS_DETREMATE 	=	NULL,
        DIR_DETREMATE 	=	NULL,
        FEC_DETREMATE 	=	NULL,
        DES_DETREMATE	=	NULL,
        FLG_CONTIENE	=	0
WHERE	ID_DETREMATE	=   IN_ID_DETREMATE;

RETURN 0;  

END$$
DELIMITER ;


    