/*PRUEBAS*/

SELECT	*
FROM	REMATE.REM_DET_REMATE;

SELECT 	REMATE.AGREGA_DET_REMATE(5,'PRUEBA','PRUEBA','01-01-1991 24:00','PRUEBA DESCRIPCION');

SELECT	REMATE.BORRA_DET_REMATE(5);

SELECT	REMATE.AGREGA_MAIL_REMATE('julio 2','ju.courbis@gmail.com');

SELECT 	REMATE.SUBE_ARCHIVO_REMATE(1,'PRUEBA','01-01-1991 24:00','PRUEBA DESCRIPCION','PRUEBA',10);

SELECT *
FROM	REM_ARCHIVO_REMATE