CREATE DATABASE REMATE;

USE REMATE;

DROP TABLE IF EXISTS REMATE.REM_DET_REMATE;

CREATE TABLE REMATE.REM_DET_REMATE
(
ID_DETREMATE	INT 	AUTO_INCREMENT,
GLS_DETREMATE	VARCHAR(30),
DIR_DETREMATE	VARCHAR(50),
FEC_DETREMATE	VARCHAR(20),
DES_DETREMATE  VARCHAR(8000),
PRIMARY KEY (ID_DETREMATE)
);

